//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_THUCUNG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public string ID_HoaDon { get; set; }
        public string ID_ThanhVien { get; set; }
        public string ID_TTDV { get; set; }
        public string ID_Chuong { get; set; }
        public Nullable<System.DateTime> ThoiGianNhan { get; set; }
        public Nullable<System.DateTime> ThoiGianTra { get; set; }
        public Nullable<decimal> TongTien { get; set; }
        public string TinhTrangHD { get; set; }
    
        public virtual Chuong Chuong { get; set; }
        public virtual ThanhVien ThanhVien { get; set; }
        public virtual ThanhToanDV ThanhToanDV { get; set; }
    }
}
