//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_THUCUNG.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QL_THUCUNGEntities : DbContext
    {
        public QL_THUCUNGEntities()
            : base("name=QL_THUCUNGEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Chuong> Chuongs { get; set; }
        public virtual DbSet<DichVu> DichVus { get; set; }
        public virtual DbSet<DonGia> DonGias { get; set; }
        public virtual DbSet<HoaDon> HoaDons { get; set; }
        public virtual DbSet<ThanhToanDV> ThanhToanDVs { get; set; }
        public virtual DbSet<ThanhVien> ThanhViens { get; set; }
        public virtual DbSet<CTTTDV> CTTTDVs { get; set; }
    
        public virtual int Chuong_TimKiem(string iD_Chuong, string tenChuong, string tinhTrangChuong, string iD_Gia, string hoatdong)
        {
            var iD_ChuongParameter = iD_Chuong != null ?
                new ObjectParameter("ID_Chuong", iD_Chuong) :
                new ObjectParameter("ID_Chuong", typeof(string));
    
            var tenChuongParameter = tenChuong != null ?
                new ObjectParameter("TenChuong", tenChuong) :
                new ObjectParameter("TenChuong", typeof(string));
    
            var tinhTrangChuongParameter = tinhTrangChuong != null ?
                new ObjectParameter("TinhTrangChuong", tinhTrangChuong) :
                new ObjectParameter("TinhTrangChuong", typeof(string));
    
            var iD_GiaParameter = iD_Gia != null ?
                new ObjectParameter("ID_Gia", iD_Gia) :
                new ObjectParameter("ID_Gia", typeof(string));
    
            var hoatdongParameter = hoatdong != null ?
                new ObjectParameter("Hoatdong", hoatdong) :
                new ObjectParameter("Hoatdong", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Chuong_TimKiem", iD_ChuongParameter, tenChuongParameter, tinhTrangChuongParameter, iD_GiaParameter, hoatdongParameter);
        }
    
        public virtual ObjectResult<TimKiem_Result> TimKiem(string tuKhoa)
        {
            var tuKhoaParameter = tuKhoa != null ?
                new ObjectParameter("TuKhoa", tuKhoa) :
                new ObjectParameter("TuKhoa", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TimKiem_Result>("TimKiem", tuKhoaParameter);
        }
    
        public virtual int TimKiem_DV(string ma, string ten, string giatu, string giaden)
        {
            var maParameter = ma != null ?
                new ObjectParameter("Ma", ma) :
                new ObjectParameter("Ma", typeof(string));
    
            var tenParameter = ten != null ?
                new ObjectParameter("Ten", ten) :
                new ObjectParameter("Ten", typeof(string));
    
            var giatuParameter = giatu != null ?
                new ObjectParameter("Giatu", giatu) :
                new ObjectParameter("Giatu", typeof(string));
    
            var giadenParameter = giaden != null ?
                new ObjectParameter("Giaden", giaden) :
                new ObjectParameter("Giaden", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TimKiem_DV", maParameter, tenParameter, giatuParameter, giadenParameter);
        }
    }
}
